function output_txt = update_datatip(obj, event_obj)
% Display the position of the data cursor
% obj          Currently not used (empty)
% event_obj    Handle to event object
% output_txt   Data cursor text string (string or cell array of strings).

userdata = get(get(event_obj,'Target'), 'UserData');

pos = get(event_obj,'Position');
output_txt = {...
    userdata.plane, ...
    ['freq: ',num2str(pos(1),4) ' Hz'],...
    [userdata.spectrum_name ': ',num2str(pos(2),4) ' ' userdata.spectrum_unit], ...
    userdata.legend{:} ...
    };